
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.cpu    = "1"
    vb.memory = "5120"
  end
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "./playbook/server.yml" 
  end
end