- hosts: all
  user: vagrant
  become: yes
  tasks:
    - name: install bind-utils
      yum: name=bind-utils state=present

    - name: install yum-utils
      yum: name=yum-utils state=present

    - name: add docker repo
      shell: "sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
      args:
        chdir: "/etc/yum.repos.d"
        creates: docker-ce.repo

    - name: install docker-ce
      yum: name=docker-ce state=present

    - name: add group
      user: name=vagrant groups=docker append=yes
      tags: dockerhost
      become: True

    - name: restart docker
      systemd:
        name: docker.service
        state: restarted
        daemon_reload: yes
        enabled: yes

    - name: ensure docker-compose is installed and available
      get_url:
        url : https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_machine}}
        dest: /usr/local/bin/docker-compose
        owner: vagrant
        group: vagrant
        mode: 'u+x,g+x'
        